# Generated by Django 3.2.25 on 2024-07-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_ingredient_recipe_ingredient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="ingredient",
            new_name="ingredients",
        ),
    ]
