# Generated by Django 3.2.25 on 2024-07-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_recipe_iamge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="iamge",
            new_name="image",
        ),
    ]
